In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4]) # generally holds single type of data type.
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr[0] # indexing start from zero.

np.int64(1)

In [8]:
arr[-1] # reverse indexing ...

np.int64(4)

In [9]:
print(arr)
# changing the original arr.
arr[1] = 10 # numpy array are volatiles we can change the value of any index.
print(arr)

[1 2 3 4]
[ 1 10  3  4]


In [10]:
arr[2]+arr[3]

np.int64(7)