In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
# starting from (0,5] including start, but not including last.
arr[0:5]

array([1, 2, 3, 4, 5])

In [4]:
# reversing the original array.
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [5]:
# -ve slicing starting from -3 (include) and -1 (not included).
arr[-3:-1]

array([7, 8])

In [6]:
print(arr[1:5:2]) # step steps at a time.

[2 4]
